name: controle_carrinho
description: Um novo projeto Flutter.

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.2.2

flutter:
  uses-material-design: true
